

---
- name: Check /etc/hosts file
  hosts: all
  tasks: 
    - shell: cat /etc/hosts
      register: result
    - debug:
        var: result.stdout

- name: Play2
  host: all
  tasks:
    - debug:
        var: result.rc

#ansible-playbook -i inventory playbook.yaml -v