# Show Fact gathered at start of play
---
- name: Print Hello message
  hosts: all
  tasks:
    - debug:
        msg: Hello from Ansible

# Show facts
---
- name: Print Facts
  hosts: all
  tasks:
    - debug:
        var: ansible_facts

# Gather no facts
---
- name: Print Facts
  hosts: all
  gather_facts: no
  tasks:
    - debug:
        var: ansible_facts