#Command Module
-
  name: Play1
  hosts: localhost
  become: true
  tasks:
    - command: date
      name: Execute date command

    - command: cat /etc/resolv.conf
      name: Display content

    - command: cat resolv.conf chdir=/etc
      name: Display content

    - command: mkdir folder creates=/folder
      name: Create folder