# Ansible Ad-Hoc commands just to test connectivity bw ansiblecontroller and target servers
-
  name: Play1
  hosts: all
  become: true
  tasks:
    - ping:
# or use below adhoc command to test the connectivity
#ansible -m ping all
# to run a command instead of ping
#ansible -a 'cat /etc/hosts' all


-
  name: Play2
  hosts: all
  become: true
  tasks:
    - command: date
      name: Execute date command

# To see verbose output with date outputs
# ansible-playbook playbook.yaml -v 

