
# Host Scope Variable
---
- name: Play
  host: all
  tasks:
    - debug:
        msg: '{{ dns_server }}'
  


# Play Scope variable
---
- name: Play1
  hosts: web1
  vars:
    ntp_server: 10.1.1.1
  tasks:
    - debug:
        var: ntp_server

- name: Play2
  host: web1
  tasks:
    - debug:
        var: ntp_server

# Global Scope variable
# ansible-playbook playbook.yaml --extra-vars ntp_server=10.5.5.7
---
- name: Play1
  hosts: web1
  vars:
    ntp_server: 10.1.1.1
  tasks:
    - debug:
        var: ntp_server

- name: Play2
  host: web1
  tasks:
    - debug:
        var: ntp_server